import type {
  Restaurant,
  MenuItem,
  Call,
  Order,
  PlatformStats,
  InfraService,
  AuditLog,
  Subscription,
  RestaurantUser,
} from '@/types/database.types';

export const MOCK_RESTAURANT: Restaurant = {
  id: 'rest-mamas-pizzeria-001',
  name: "Mama's Pizzeria",
  phone_number: '+61 2 8399 1234',
  telnyx_number: '+61 2 8123 4567',
  plan_id: 'growth',
  active: true,
  ai_instructions:
    'Warm Italian greeting. Recommend Truffle Mushroom pizza and Tiramisu. Offer sparkling or still water for drinks.',
  timezone: 'Australia/Sydney',
  health_score: 98,
  pos_provider: 'Square POS',
  pos_status: 'connected',
  status: 'active',
  mrr: 249,
  calls_month: 842,
  orders_month: 512,
  completion_rate: 96.4,
  created_at: '2026-06-15T08:30:00Z',
};

export const MOCK_FLEET_RESTAURANTS: Restaurant[] = [
  MOCK_RESTAURANT,
  {
    id: 'rest-bondi-burger-002',
    name: 'Bondi Burger Co',
    phone_number: '+61 2 9130 5522',
    telnyx_number: '+61 2 8123 4568',
    plan_id: 'enterprise',
    active: true,
    ai_instructions: 'Casual beach vibe. Ask about combo meals.',
    timezone: 'Australia/Sydney',
    health_score: 95,
    pos_provider: 'Lightspeed',
    pos_status: 'connected',
    status: 'active',
    mrr: 499,
    calls_month: 1420,
    orders_month: 980,
    completion_rate: 98.1,
    created_at: '2026-05-10T11:00:00Z',
  },
  {
    id: 'rest-little-italy-003',
    name: 'Little Italy Carlton',
    phone_number: '+61 3 9347 1199',
    telnyx_number: '+61 3 8123 4569',
    plan_id: 'growth',
    active: true,
    ai_instructions: 'Traditional Italian tone. Check daily specials.',
    timezone: 'Australia/Melbourne',
    health_score: 92,
    pos_provider: 'Square POS',
    pos_status: 'connected',
    status: 'active',
    mrr: 249,
    calls_month: 670,
    orders_month: 420,
    completion_rate: 94.8,
    created_at: '2026-06-01T09:15:00Z',
  },
  {
    id: 'rest-dragon-dumpling-004',
    name: 'Golden Dragon Dumplings',
    phone_number: '+61 7 3252 8844',
    telnyx_number: '+61 7 8123 4570',
    plan_id: 'starter',
    active: true,
    ai_instructions: 'Fast and efficient. Recommend soup dumplings.',
    timezone: 'Australia/Brisbane',
    health_score: 88,
    pos_provider: 'Kounta',
    pos_status: 'syncing',
    status: 'active',
    mrr: 149,
    calls_month: 310,
    orders_month: 195,
    completion_rate: 91.2,
    created_at: '2026-07-20T14:45:00Z',
  },
  {
    id: 'rest-byron-burrito-005',
    name: 'Byron Bay Burritos',
    phone_number: '+61 2 6685 4321',
    telnyx_number: '+61 2 8123 4571',
    plan_id: 'growth',
    active: true,
    ai_instructions: 'Friendly surfer vibe. Highlight vegan options.',
    timezone: 'Australia/Sydney',
    health_score: 79,
    pos_provider: 'Square POS',
    pos_status: 'error',
    status: 'at_risk',
    mrr: 249,
    calls_month: 520,
    orders_month: 310,
    completion_rate: 82.5,
    created_at: '2026-08-05T16:20:00Z',
  },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-001',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Margherita Classica',
    description: 'San Marzano tomatoes, buffalo mozzarella, fresh basil, extra virgin olive oil',
    price_cents: 2200,
    price: 22.0,
    category: 'Pizza',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-002',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Diavola Piccante',
    description: 'Spicy calabrese salami, fior di latte, chilli flakes, hot honey drizzle',
    price_cents: 2600,
    price: 26.0,
    category: 'Pizza',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-003',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Truffle & Mushroom',
    description: 'Wild portobello mushrooms, black truffle cream, thyme, fior di latte',
    price_cents: 2800,
    price: 28.0,
    category: 'Pizza',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-004',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Quattro Formaggi',
    description: 'Gorgonzola dolce, aged parmesan, taleggio, buffalo mozzarella',
    price_cents: 2500,
    price: 25.0,
    category: 'Pizza',
    available: false,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-005',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Rigatoni Carbonara',
    description: 'Crispy guanciale, pecorino romano, fresh egg yolk, cracked black pepper',
    price_cents: 2400,
    price: 24.0,
    category: 'Pasta',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-006',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: "Penne all'Arrabbiata",
    description: 'Garlic, fiery red chillies, crushed Roma tomatoes, fresh parsley',
    price_cents: 2100,
    price: 21.0,
    category: 'Pasta',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-007',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Garlic Rosemary Focaccia',
    description: 'Woodfired flatbread, sea salt flakes, roasted garlic oil, fresh rosemary',
    price_cents: 1200,
    price: 12.0,
    category: 'Starters',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'item-008',
    restaurant_id: 'rest-mamas-pizzeria-001',
    name: 'Traditional Tiramisu',
    description: 'Savoiardi soaked in espresso, mascarpone mousse, cocoa powder',
    price_cents: 1400,
    price: 14.0,
    category: 'Desserts',
    available: true,
    created_at: '2026-06-15T09:00:00Z',
  },
];

export const MOCK_LIVE_CALLS: Call[] = [
  {
    id: 'call-live-001',
    restaurant_id: 'rest-mamas-pizzeria-001',
    restaurant_name: "Mama's Pizzeria",
    caller_number: '+61 412 893 210',
    caller_phone: '+61 412 893 210',
    state: 'TAKING_ORDER',
    started_at: new Date(Date.now() - 102000).toISOString(),
    ended_at: null,
    duration_seconds: 102,
    transcript: [
      {
        role: 'ai',
        text: "Buonasera! Welcome to Mama's Pizzeria. What can I get started for pickup tonight?",
        time: '00:02',
      },
      {
        role: 'customer',
        text: 'Hi! Can I order two Margherita pizzas and one garlic focaccia please?',
        time: '00:15',
      },
      {
        role: 'ai',
        text: "Wonderful! That's two Margheritas and one Garlic Rosemary Focaccia. Would you like to add any drinks or dessert?",
        time: '00:28',
      },
    ],
    stt_confidence: 0.98,
    livekit_room: 'room_mamas_8921',
    sentiment: 'positive',
    order_items_preview: '2x Margherita, 1x Garlic Focaccia',
  },
  {
    id: 'call-live-002',
    restaurant_id: 'rest-mamas-pizzeria-001',
    restaurant_name: "Mama's Pizzeria",
    caller_number: '+61 498 765 432',
    caller_phone: '+61 498 765 432',
    state: 'CONFIRMING',
    started_at: new Date(Date.now() - 54000).toISOString(),
    ended_at: null,
    duration_seconds: 54,
    transcript: [
      {
        role: 'ai',
        text: 'I have 1x Rigatoni Carbonara and 1x Traditional Tiramisu. Total is $38.00. Ready for payment?',
        time: '00:42',
      },
      {
        role: 'customer',
        text: 'Yes, that sounds great.',
        time: '00:48',
      },
    ],
    stt_confidence: 0.96,
    livekit_room: 'room_mamas_8922',
    sentiment: 'positive',
    order_items_preview: '1x Carbonara, 1x Tiramisu',
  },
  {
    id: 'call-live-003',
    restaurant_id: 'rest-bondi-burger-002',
    restaurant_name: 'Bondi Burger Co',
    caller_number: '+61 423 111 222',
    caller_phone: '+61 423 111 222',
    state: 'TRANSFER_TO_HUMAN',
    started_at: new Date(Date.now() - 135000).toISOString(),
    ended_at: null,
    duration_seconds: 135,
    transcript: [
      {
        role: 'customer',
        text: 'Does your gluten-free bun contain sesame seeds? Severe allergy.',
        time: '00:30',
      },
      {
        role: 'ai',
        text: 'Because of your severe allergy, I am connecting you immediately with a duty manager. Please stay on the line.',
        time: '00:42',
      },
    ],
    stt_confidence: 0.94,
    livekit_room: 'room_bondi_8923',
    sentiment: 'neutral',
    order_items_preview: 'Allergy Inquiry Escalation',
  },
];

export const MOCK_RECENT_ORDERS: Order[] = [
  {
    id: 'ord-8921',
    call_id: 'call-hist-101',
    restaurant_id: 'rest-mamas-pizzeria-001',
    items: [
      { name: 'Margherita Classica', qty: 2, price_cents: 2200 },
      { name: 'Garlic Rosemary Focaccia', qty: 1, price_cents: 1200 },
    ],
    total_cents: 5600,
    total_amount: 56.0,
    state: 'LINK_SENT',
    pos_order_id: null,
    customer_phone: '+61 412 893 210',
    customer_name: 'Sarah M.',
    created_at: new Date(Date.now() - 240000).toISOString(),
  },
  {
    id: 'ord-8920',
    call_id: 'call-hist-100',
    restaurant_id: 'rest-mamas-pizzeria-001',
    items: [
      { name: 'Diavola Piccante', qty: 1, price_cents: 2600 },
      { name: 'Traditional Tiramisu', qty: 1, price_cents: 1400 },
    ],
    total_cents: 4000,
    total_amount: 40.0,
    state: 'PAID',
    pos_order_id: 'sq_ord_9011a',
    customer_phone: '+61 498 765 432',
    customer_name: 'David K.',
    created_at: new Date(Date.now() - 720000).toISOString(),
  },
  {
    id: 'ord-8919',
    call_id: 'call-hist-099',
    restaurant_id: 'rest-mamas-pizzeria-001',
    items: [
      { name: 'Truffle & Mushroom', qty: 2, price_cents: 2800 },
      { name: 'Rigatoni Carbonara', qty: 1, price_cents: 2400 },
    ],
    total_cents: 8000,
    total_amount: 80.0,
    state: 'SYNCED',
    pos_order_id: 'sq_ord_9010b',
    customer_phone: '+61 455 332 110',
    customer_name: 'Liam T.',
    created_at: new Date(Date.now() - 1140000).toISOString(),
  },
];

export const MOCK_PLATFORM_STATS: PlatformStats = {
  activeCallsCount: 23,
  totalVenues: 487,
  todayCallsCount: 3412,
  todayOrdersCount: 1894,
  todayRevenueCents: 6843000,
  mrrCents: 9480000,
  grossMarginPercent: 87.2,
  avgCallDurationSeconds: 98,
  cogsPerMinuteAud: 0.062,
  sttAccuracyPercent: 96.8,
  uptimePercent: 99.98,
};

export const MOCK_INFRA_SERVICES: InfraService[] = [
  {
    name: 'Telnyx SIP Inbound & Media',
    category: 'voice',
    status: 'operational',
    latencyMs: 34,
    uptimePercent: 99.99,
    errorRatePercent: 0.01,
    metricLabel: 'Audio Jitter',
    metricValue: '4.2ms',
  },
  {
    name: 'Deepgram Flux STT (AU English)',
    category: 'voice',
    status: 'operational',
    latencyMs: 62,
    uptimePercent: 99.98,
    errorRatePercent: 0.02,
    metricLabel: 'Time To First Token',
    metricValue: '58ms',
  },
  {
    name: 'OpenAI GPT-4.1 Reasoning & Tools',
    category: 'ai',
    status: 'operational',
    latencyMs: 240,
    uptimePercent: 99.95,
    errorRatePercent: 0.05,
    metricLabel: 'Inference Latency',
    metricValue: '215ms',
  },
  {
    name: 'ElevenLabs Streaming TTS',
    category: 'voice',
    status: 'operational',
    latencyMs: 180,
    uptimePercent: 99.97,
    errorRatePercent: 0.03,
    metricLabel: 'Audio Synthesis',
    metricValue: '172ms',
  },
  {
    name: 'LiveKit Cloud WebRTC Cluster',
    category: 'voice',
    status: 'operational',
    latencyMs: 28,
    uptimePercent: 100,
    errorRatePercent: 0.0,
    metricLabel: 'Packet Loss',
    metricValue: '0.04%',
  },
  {
    name: 'Stripe SMS Payment Links',
    category: 'payment',
    status: 'operational',
    latencyMs: 85,
    uptimePercent: 100,
    errorRatePercent: 0.0,
    metricLabel: 'Webhook Dispatch',
    metricValue: '92ms',
  },
  {
    name: 'Supabase Postgres + pgvector',
    category: 'infra',
    status: 'operational',
    latencyMs: 18,
    uptimePercent: 99.99,
    errorRatePercent: 0.0,
    metricLabel: 'RAG Cosine Query',
    metricValue: '12ms',
  },
  {
    name: 'Upstash Redis Session Store',
    category: 'infra',
    status: 'operational',
    latencyMs: 4,
    uptimePercent: 100,
    errorRatePercent: 0.0,
    metricLabel: 'Session Read',
    metricValue: '3.8ms',
  },
  {
    name: 'Square POS Webhook Dispatcher',
    category: 'pos',
    status: 'operational',
    latencyMs: 142,
    uptimePercent: 99.91,
    errorRatePercent: 0.09,
    metricLabel: 'Push Sync Time',
    metricValue: '138ms',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-09-03T11:58:22Z',
    event_type: 'ORDER',
    actor: 'AI_AGENT_MAMAS',
    resource: 'Order #TB-8921',
    details: 'Order confirmed with 2 items ($56.00 AUD). Payment link SMS dispatched via Telnyx.',
    ip_address: '13.239.12.84',
    status: 'success',
  },
  {
    id: 'log-102',
    timestamp: '2026-09-03T11:56:10Z',
    event_type: 'ESCALATION',
    actor: 'AI_AGENT_BONDI',
    resource: 'Call #call-live-003',
    details:
      'Escalation triggered: caller mentioned severe allergy keyword. Live call transferred to venue manager phone.',
    ip_address: '13.239.12.85',
    status: 'warning',
  },
  {
    id: 'log-103',
    timestamp: '2026-09-03T11:45:00Z',
    event_type: 'POS',
    actor: 'CELERY_SYNC_WORKER',
    resource: 'Order #TB-8919',
    details: 'Square POS push succeeded. Order #sq_ord_9010b printed in kitchen.',
    ip_address: '10.0.4.12',
    status: 'success',
  },
  {
    id: 'log-104',
    timestamp: '2026-09-03T11:30:15Z',
    event_type: 'BILLING',
    actor: 'STRIPE_WEBHOOK',
    resource: 'Subscription #sub_mamas_01',
    details: 'Monthly Growth plan renewed ($249.00 AUD). Invoice paid successfully.',
    ip_address: '54.187.205.235',
    status: 'success',
  },
  {
    id: 'log-105',
    timestamp: '2026-09-03T11:15:40Z',
    event_type: 'SYSTEM',
    actor: 'HEALTH_CHECK_CRON',
    resource: 'Telnyx SIP Trunk',
    details: 'Synthetic SIP ping response 34ms. All 12 trunks healthy.',
    ip_address: '127.0.0.1',
    status: 'info',
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-001',
    restaurant_id: 'rest-mamas-pizzeria-001',
    restaurant_name: "Mama's Pizzeria",
    plan_id: 'growth',
    plan_name: 'Growth ($249/mo)',
    stripe_subscription_id: 'sub_live_mamas991',
    status: 'active',
    current_period_end: '2026-09-30T00:00:00Z',
    created_at: '2026-06-15T08:30:00Z',
  },
  {
    id: 'sub-002',
    restaurant_id: 'rest-bondi-burger-002',
    restaurant_name: 'Bondi Burger Co',
    plan_id: 'enterprise',
    plan_name: 'Enterprise ($499/mo)',
    stripe_subscription_id: 'sub_live_bondi882',
    status: 'active',
    current_period_end: '2026-09-30T00:00:00Z',
    created_at: '2026-05-10T11:00:00Z',
  },
];

export const MOCK_USERS: RestaurantUser[] = [
  {
    id: 'usr-001',
    restaurant_id: 'rest-mamas-pizzeria-001',
    user_id: 'auth-user-001',
    name: 'Marco Rossi',
    email: 'marco@mamaspizzeria.com.au',
    role: 'owner',
    created_at: '2026-06-15T08:30:00Z',
  },
  {
    id: 'usr-002',
    restaurant_id: 'rest-mamas-pizzeria-001',
    user_id: 'auth-user-002',
    name: 'Lucia Rossi',
    email: 'lucia@mamaspizzeria.com.au',
    role: 'staff',
    created_at: '2026-06-20T10:00:00Z',
  },
  {
    id: 'usr-003',
    restaurant_id: 'rest-bondi-burger-002',
    user_id: 'auth-user-003',
    name: 'Jack Miller',
    email: 'jack@bondiburger.com.au',
    role: 'owner',
    created_at: '2026-05-10T11:00:00Z',
  },
];
